//
// Created by chris on 2/4/24.
//

#ifndef SRECORD_ASSEMBLY_ENCRIPTING_SRECORDENCODE_H
#define SRECORD_ASSEMBLY_ENCRIPTING_SRECORDENCODE_H

#include "SRecordEncode.c"

#endif //SRECORD_ASSEMBLY_ENCRIPTING_SRECORDENCODE_H
